version: '3.7'

services:

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile.php
    container_name: ${APP_NAME}-php
    volumes:
      - type: bind
        target: /var/www/html
        source: ./app

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: ${APP_NAME}-webserver
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html
    ports:
      - '${PORT_SERVER}:80'
      # - '443:443'
    environment:
      - "DOMAIN=${DOMAIN}"

  postgres:
    image: postgres:15
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
       - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${PORT_BDD}:5432

volumes:
  db_data: