version: '3.1'

services:

  # php-fpm:
  web:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: ${APP_NAME}-nginx
    volumes:
      - type: bind
        source: ./project
        target: /project
    ports:
      - '8080:80'
      # - '443:443'
    environment:
      - "DOMAIN=${DOMAIN}"


#   db:
#     image: postgres
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_DB: ${POSTGRES_DB}
#       PGDATA: /var/lib/postgresql/data
#     volumes:
#        - postgres:/var/lib/postgresql/data
#     networks:
#       - postgres
#     restart: unless-stopped


# networks:
#   postgres:
#     driver: bridge

# volumes:
#   postgres: